FROM python:3.10

LABEL maintainer="Alexius Dias and Pedro Henrique Souza"
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD [ "python", "main.py" ]