
services:
  bot:
    build: .
    command: python3 main.py
    volumes:
      - .:/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - D:/MongoDB/server:/data/db
    restart: always
