
"""
Settings for the bot. Highly customizable.

This module contains various configuration settings for the bot, including cooldowns, prices, and limits.

"""
# Cooldown settings (in seconds)

SPAM_COOLDOWN = 1 # Cooldown for spam commands
REGULAR_COOLDOWN = 3.5 # Cooldown for regular commands
QUEUE_COOLDOWN = 90 # Cooldown for queue commands

# Hunger Games command settings

HUNGER_GAMES_WAIT_TIME= 60 # Wait time before a hunger games match starts (in seconds)
HUNGER_GAMES_MATCH_VALUE = 75 # The prize that the user has to pay to join the match
HUNGER_GAMES_PRIZE = 50 # The weight that each tribute's that is in the match will be multiplied by to determine the total prize
MIN_TRIBUTES = 4 # The minimum number of tributes that must be in the match for it to start
MAX_TRIBUTES = 30 # The maximum number of tributes that can be in the match

# Farm settings

CHICKEN_DEFAULT_VALUE = 400 # controls the minimum value of a chicken that can generate in the market.
DEFAULT_FARM_SIZE = 8 # controls the default farm size
OFFER_EXPIRE_TIME = 168 # controls the time it takes for an offer to expire (in hours)
MAX_BENCH = 5 # controls the maximum number of chickens that can be on the bench
MAX_CORN_LIMIT = 2553 # controls the maximum corn limit
MAX_PLOT_LIMIT = 20 # controls the maximum plot limit
CORN_PER_PLOT = 100 # controls the amount of corn that can be produced per plot
FARM_DROP = 7200 # controls the time it takes for the chickens in a farm to drop eggs (in seconds)
ROLL_PER_HOUR = 3600 # controls the time it takes for the user to reset their rolls in the market (in seconds)
MAX_PLOT_TAX_VALUE = 200 # controls the maximum tax value for the plots
MAX_CORN_TAX_VALUE = 150 # controls the maximum tax value for the corn
MAX_FARM_TAX_VALUE = 300 # controls the maximum tax value for the farm
MAX_EGG_GENERATED = 1000000 # controls the limit shown of total eggs generated by a farm
DEFAULT_ROLLS = 10 # controls the default number of rolls in the market
FARMER_PRICE = 5000 # controls the price of the farmer upgrade
CHICKENS_GENERATED = 8 # controls how many chickens will generated with the market command.

# Hybrid command settings

TAX = .15 # controls the donate command tax and buying a chicken from the player market tax
USER_SALARY_DROP = 3600 # controls the time it takes for the user to gain their salary (in seconds)