tips = {
    0: "You earn 1 eggbux every 10 seconds of call time.",
    1: "The currency name is eggbux.",
    2: "Type !casino to gamble your eggbux.",
    3: "You can buy titles with eggbux that generates passive income forever.",
    4: "Type !titles to see the available titles.",
    5: "You can start a farm and buy chickens with eggbux.",
    6: "Type !farm to see your farm.",
    7: "The market command generates 8 random chickens.",
    8: "Type !market to generate 8 random chickens.",
    9: "You can trade chickens with other players, using !trade command.",
    10:"You can gift chickens to other players, using !gift command.",
    11: "You can register your chicken to the player market, using !offer command.",
    12: "You can do up to 15 different searches in the player market with the !search command.",
    13: "You can view your market offers, using !offers, it comes with an optional user parameter.",
    14: "You can extend your bank's capacity with the !ubl command.",
    15: "Your chickens require daily attention or they have a chance of devolving.",
    16: "You can gain permanent buffs for your farm with the !farmers command.",
    17: "You can view the top 10 users with the most points using the !leaderboard command.",
    18: "You can see the hourly income of your farm with the !fp command, it comes with an optional user parameter.",
    19: "You can donate eggbux to other players using the !donate command.",
    20: "Every plot of corn produces 25 corn every hour, you can expand your plot limit with the !bp command.",
    21: "You can expand your corn limit with the !ucl command.",
    22: "You can sell corn for a third of the price.",
    23: "You can buy corn with eggbux.",
    24: "You can start a hunger games event with the !hg command, the minimum number of players is 4.",
    25: "This message is a tip.",
    26: "The maximum plot limit is 8.",
    27: "Your chickens wait for you to feed them.",
    28: "This bot was made by a human.",
    29: "The formula for the eggs produced by a chicken is: (eggs_per_hour * happiness) / 100.",
    30: "The formula for the eggs produced by a chicken is: (eggs_per_hour * upkeep_multiplier)",
    31: "You need to pay hourly for the upkeep of your chickens.",
    32: "The upkeep multiplier for the chickens has two functions, it regulates the eggs produced and the upkeep cost.",
    33: "You can evolve two chickens of the same type to the next rarity",
    34: "Everytime you don't have money to maintain your chickens, one of them will randomly be picked to be deleted.",
}